#!/usr/bin/with-contenv bash

USER="relayer"

HOME="$(eval echo ~$USER)"

DAEMON="$(which centralized-relay) start --home $HOME"

RLY_CMD="exec $DAEMON"

exec s6-setuidgid relayer /bin/bash -c "$RLY_CMD"
