#!/usr/bin/with-contenv bash

USER="${RELAYER_USER:-relayer}"

HOME="$(eval echo ~$USER)"

RELAY_HOME="${RELAY_HOME:-/data}"

SOCKET_DIR="${SOCKET_DIR:-/var/run/relayer}"

mkdir -p "$SOCKET_DIR" "$RELAY_HOME"

chown -R $USER:$USER "$RELAY_HOME"

chown -R $USER $SOCKET_DIR

chown -R $USER $HOME

chmod 775 $SOCKET_DIR