#!/usr/bin/with-contenv bash

USER="${RELAYER_USER:-relayer}"

HOME="$(eval echo ~$USER)"

DATA_DIR="${DATA_DIR:-$HOME/.centralized-relay}"

SOCKET_DIR="${SOCKET_DIR:-/var/run/relayer}"

mkdir -p "$DATA_DIR" "$SOCKET_DIR"

chown -R $USER:$USER "$DATA_DIR"

chown -R $USER $SOCKET_DIR

chmod 775 $SOCKET_DIR