name: Build and Push

on:
  push:
    tags:
      - v*
  repository_dispatch:
    types: [trigger-build]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set TAG_NAME
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "TAG_NAME=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - id: docker_meta
        name: Get metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            iconcommunity/relay-base:latest
            iconcommunity/relay-base:${{ env.TAG_NAME }}
            iconcommunity/centralized-relay:latest
            iconcommunity/centralized-relay:${{ env.TAG_NAME }}
            iconcommunity/relayer-admin-dashboard:latest
            iconcommunity/relayer-admin-dashboard:${{ env.TAG_NAME }}

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: ./base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iconcommunity/relay-base:latest
            iconcommunity/relay-base:${{ env.TAG_NAME }}

      - name: Build relayer image
        uses: docker/build-push-action@v6
        with:
          context: ./relayer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iconcommunity/centralized-relay:latest
            iconcommunity/centralized-relay:${{ env.TAG_NAME }}

      - name: Build admin dashboard image
        uses: docker/build-push-action@v6
        with:
          context: ./admin-dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iconcommunity/relayer-admin-dashboard:latest
            iconcommunity/relayer-admin-dashboard:${{ env.TAG_NAME }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v2.3.0

      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
