name: Build and Push

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and push'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base image
        id: build-and-push-base
        uses: docker/build-push-action@v6
        with:
          context: ./base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iconcommunity/relay-base:latest
            iconcommunity/relay-base:${{ inputs.tag }}

      - name: Build relayer image
        id: build-and-push-relayer
        uses: docker/build-push-action@v6
        with:
          context: ./relayer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iconcommunity/centralized-relay:latest
            iconcommunity/centralized-relay:${{ inputs.tag }}

      - name: Build nginx image
        id: build-and-push-admin-dashboard
        uses: docker/build-push-action@v6
        with:
          context: ./admin-dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            iconcommunity/relayer-admin-dashboard:latest
            iconcommunity/relayer-admin-dashboard:${{ inputs.tag }}

      - name: Sign base image
        uses: ./.github/workflows/sign-image.yml
        with:
          tags: "iconcommunity/relay-base:latest iconcommunity/relay-base:${{ inputs.tag }}"
          digest: ${{ steps.build-and-push-base.outputs.digest }}

      - name: Sign relayer image
        uses: ./.github/workflows/sign-image.yml
        with:
          tags: "iconcommunity/centralized-relay:latest iconcommunity/centralized-relay:${{ inputs.tag }}"
          digest: ${{ steps.build-and-push-relayer.outputs.digest }}

      - name: Sign nginx image
        uses: ./.github/workflows/sign-image.yml
        with:
          tags: "iconcommunity/relayer-admin-dashboard:latest iconcommunity/relayer-admin-dashboard:${{ env.TAG_NAME }}"
          digest: ${{ steps.build-and-push-admin-dashboard.outputs.digest }}

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./base/Dockerfile
            ./relayer/Dockerfile
            ./admin-dashboard/Dockerfile
            ./docker-compose.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.tag }}
          make_latest: true
          generate_release_notes: true
